name: Build SunamoStringGetLines

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoStringGetLines
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringGetLines/SunamoStringGetLines.csproj

    - name: Build
      run: dotnet build SunamoStringGetLines/SunamoStringGetLines.csproj --configuration Release --no-restore

  test:
    name: Test SunamoStringGetLines.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringGetLines.Tests/SunamoStringGetLines.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoStringGetLines.Tests/SunamoStringGetLines.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoStringGetLines.Tests/SunamoStringGetLines.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
